<a href="https://colab.research.google.com/github/ankalagigaurave/NLP-Sem-VI/blob/main/Assignment/NLP_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all
       | 
       | Downloading package abc to /root/nltk_data...
       |   Package abc is already up-to-date!
       | Downloading package alpino to /root/nltk_data...
       |   Package alpino is already up-to-date!
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Package biocreative_ppi is already up-to-date!
       | Downloading package brown to /root/nltk_data...
       |   Package brown is already up-to-date!
       | Downloading package brown_tei to /root/nltk_data...
       |   Package brown_tei is already up-to-date!
       | Downloading package cess_cat to /root/nltk_data...
       |   Package cess_cat is already up-to-date!
       | Down

True

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from nltk.corpus import stopwords
from string import punctuation
from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer

In [3]:
df=pd.read_csv('/content/spam.csv',encoding='ISO-8859-1')
df

v1  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN
...    ...  ...        ...
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[5572 rows x 5 columns]

In [4]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis='columns', inplace=True)

In [5]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df['v1']=df['v1'].replace(['ham','spam'],[0,1])

In [7]:
df['v1']

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int64

In [8]:
import re
ls=LancasterStemmer()

corpus_stem=[]
for i in range(len(df)):
    review=re.sub('[^a-zA_Z]',' ',df['v2'][i])
    review=review.lower()
    review=review.split()
    review=[ls.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus_stem.append(review)
    
corpus_stem

['jurong point crazy avail bug n gre world la e buffet in got am wat',
 'k lar ok wif u on',
 'ree entry wkly comp win fin tkts st ay ext receiv entry quest std txt rat apply',
 'dun say ear hor c already say',
 'ah think goe usf liv around though',
 'ree sg ey darl week word back lik fun stil b ok x std chgs send rcv',
 'ven broth lik speak hey tre lik aid pat',
 'per request el el ru innaminungint urungu ettam set callertun al ress cop friend allertun',
 'valu network custom select receive priz reward claim cal laim cod alid hour',
 'ad mobl month entitl pdat latest colo mobl camer ree obl pdat',
 'gonn hom soon want talk stuff anym tonight k cri enough today',
 'chant win rom pound txt send ost p day day sand apply eply info',
 'ou week memb riz ackpot xt word www dbuk net',
 'search right word thank breath prom wont tak help grant fulfil prom ou wond bless tim',
 '',
 'obl ovy lub us credit click link next txt mess click http wap xxxmobilemovieclub com n',
 'h k watch',
 'h u remem

In [9]:
from nltk.stem import WordNetLemmatizer
lem=WordNetLemmatizer()

corpus_lem=[]
for i in range(len(df)):
    review=re.sub('[^a-zA_Z]',' ',df['v2'][i])
    review=review.lower()
    review=review.split()
    review=[lem.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus_lem.append(review)
    
corpus_lem

['jurong point crazy available bugis n great world la e buffet ine got amore wat',
 'k lar oking wif u oni',
 'ree entry wkly comp win final tkts st ay ext receive entry question std txt rate apply',
 'dun say early hor c already say',
 'ah think go usf life around though',
 'ree sg ey darling week word back like fun still b ok x std chgs send rcv',
 'ven brother like speak hey treat like aid patent',
 'per request elle elle ru innaminunginte urungu ettam set callertune allers res copy friend allertune',
 'valued network customer selected receivea prize reward claim call laim code alid hour',
 'ad mobile month entitled pdate latest colour mobile camera ree obile pdate',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'chance win rom pound txt send ost p day day sand apply eply info',
 'ou week membership rize ackpot xt word www dbuk net',
 'searching right word thank breather promise wont take help granted fulfil promise ou wonderful blessing time',
 '',
 'obi

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
CV=CountVectorizer(max_features=5000)
x_lem=CV.fit_transform(corpus_lem).toarray()
x_lem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
x_stem=CV.fit_transform(corpus_stem).toarray()
x_stem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_stem=TfidfVectorizer()
x_tf_stem=tf_stem.fit_transform(corpus_stem)
print(x_tf_stem.shape)

(5572, 5552)


In [13]:
tf_lem=TfidfVectorizer()
x_tf_lem=tf_stem.fit_transform(corpus_lem)
print(x_tf_lem.shape)

(5572, 7251)


In [14]:
y=df['v1']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x_stem,y,test_size=0.2)

In [16]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4457, 5000), (1115, 5000), (4457,), (1115,))

In [17]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB().fit(X_train,y_train)
ypred_mnb=mnb.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,ypred_mnb))
print(confusion_matrix(y_test,ypred_mnb))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       949
           1       0.87      0.91      0.89       166

    accuracy                           0.97      1115
   macro avg       0.93      0.94      0.93      1115
weighted avg       0.97      0.97      0.97      1115

[[926  23]
 [ 15 151]]


In [19]:
X_train, X_test, y_train, y_test= train_test_split(x_lem,y,test_size=0.2)
mnb=MultinomialNB().fit(X_train,y_train)
ypred_mnb_lem=mnb.predict(X_test)
print(classification_report(y_test,ypred_mnb_lem))
print(confusion_matrix(y_test,ypred_mnb_lem))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.92      0.95      0.93       149

    accuracy                           0.98      1115
   macro avg       0.95      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115

[[953  13]
 [  7 142]]


In [20]:
X_train, X_test, y_train, y_test= train_test_split(x_tf_lem,y,test_size=0.2)
mnb=MultinomialNB().fit(X_train,y_train)
ypred_mnb_tf_lem=mnb.predict(X_test)
print(classification_report(y_test,ypred_mnb_tf_lem))
print(confusion_matrix(y_test,ypred_mnb_tf_lem))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       951
           1       1.00      0.75      0.86       164

    accuracy                           0.96      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.96      0.96      0.96      1115

[[951   0]
 [ 41 123]]


In [21]:
X_train, X_test, y_train, y_test= train_test_split(x_tf_stem,y,test_size=0.2)
mnb=MultinomialNB().fit(X_train,y_train)
ypred_mnb_tf_stem=mnb.predict(X_test)
print(classification_report(y_test,ypred_mnb_tf_stem))
print(confusion_matrix(y_test,ypred_mnb_tf_stem))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       962
           1       0.97      0.72      0.83       153

    accuracy                           0.96      1115
   macro avg       0.97      0.86      0.90      1115
weighted avg       0.96      0.96      0.96      1115

[[959   3]
 [ 43 110]]


In [23]:
import imblearn
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()
x, y = rus.fit_resample(x_lem, y)
X_train, X_test, y_train, y_test= train_test_split(x,y,test_size=0.2)
mnb=MultinomialNB().fit(X_train,y_train)
ypred_mnb_lem=mnb.predict(X_test)
print(classification_report(y_test,ypred_mnb_lem))
print(confusion_matrix(y_test,ypred_mnb_lem))

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


              precision    recall  f1-score   support

           0       0.97      0.91      0.94       157
           1       0.91      0.97      0.94       142

    accuracy                           0.94       299
   macro avg       0.94      0.94      0.94       299
weighted avg       0.94      0.94      0.94       299

[[143  14]
 [  4 138]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
